language: node_js

node_js:
  - "0.10"

before_install:
  - echo $TRAVIS_OS_NAME
  - echo NODE_VERSION
  - if [ $TRAVIS_OS_NAME == "osx" ]; then rm -rf ~/.nvm fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then git clone https://github.com/creationix/nvm.git ~/.nvm fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then source ~/.nvm/nvm.sh fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then nvm install $NODE_VERSION fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then node --version fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then npm install fi

before_script:
  - npm install

script:
  - npm test

os:
  - linux
  - osx
  - windows

notifications:
  emails:
    - misaki.pink@gmail.com
  on_success: always
  on_failure: always
