language: node_js

node_js:
  - "0.10"

before_install:
  - echo $TRAVIS_OS_NAME
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
    - rm -rf ~/.nvm
    - git clone https://github.com/creationix/nvm.git ~/.nvm
    - source ~/.nvm/nvm.sh
    - nvm install $NODE_VERSION
    - node --version
    - npm install
  - fi
before_script:
  - npm install

script:
  - npm test

os:
  - linux
  - osx
  - windows

notifications:
  emails:
    - misaki.pink@gmail.com
  on_success: always
  on_failure: always
