// Generated by CoffeeScript 1.8.0
(function() {
  require("m-util");
  var hr = "_".uRepeat(20);
  var m_path = require("./index.js");

  console.log(hr);
  console.log('getPlatform():', m_path.getPlatform());
  console.log('isWindows():', m_path.isWindows());
  console.log('getPathseparator():', m_path.getPathseparator());

  console.log(hr);
  console.log('pathSplit():', m_path.pathSplit("./path/path2/path3"));
  console.log('pathSplit():', m_path.pathSplit("path/path2/path3"));

  console.log(hr);
  console.log('pathJoin():', m_path.pathJoin(['.', 'path', 'path2', 'path3']));
  console.log('pathJoin():', m_path.pathJoin(['path', 'path2', 'path3']));

}).call(this);
